### ISSUE TITLE
Wide Review Comment 2017: Timestamp syntax

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#370] opened 2017-09-27 11:02 UTC
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

The syntax of WebVTT timestamps requires that all timestamps contain a full stop character followed by three digits. This is a likely source of errors in two ways: Firstly, if a conformant processor sees a timestamp with a different number of characters (even a greater number) after the full stop, rather than returning a valid alternative time, it returns an error. This is therefore not robust to authoring errors. Secondly, a non-conformant processor that does not return an error must make a decision about how to deal with the strange number of digits. Since it is clearly defined as a "number of milliseconds" most interpretations would/should treat a timestamp such as "00:00:01.2" as having 2 milliseconds, but this is contrary to the normal mathematical representation of a fractional value, which would consider it to be 200 milliseconds. I would propose that the parser should a) append '0's after the value4 string to pad it to 3 characters if it has fewer than 3 and b) truncate the value4 string to 3 characters if it has more than 3. (rounding seems pointlessly complex when the significance is +/- 0.5ms and the user agent probably doesn't meet that level of precision anyway)

**Comment by dwsinger** [comment] 2017-09-28 20:35
We could certainly include such a recommendation ("be strict in what you produce, be lax in what you accept")

**Comment by nigelmegitt** [comment] 2017-09-29 09:19
Since the parser is defined as an algorithm, there doesn't seem to be any scope for this as a recommendation. It's either do it the current way or do it some other way. This would be a change to §5.1 at #collect-a-webvtt-timestamp

**Comment by silviapfeiffer** [comment] 2017-11-11 04:28
Hmm... it's really difficult to say what the author meant by "00:00:01.2" . Maybe they meant 2ms, but maybe they meant 200ms. Because of this, we decided to always require 3 digits to specify milliseconds. Also, we're returning an error for this cue (and thus ignoring this cue) if more or less than 3 digits are specified because it is completely unclear how to interpret it and the author needs to be informed somehow that this is unclear. It doesn't mean that the rest of the cues in the file won't be rendered.

I'd like to close this as "works for me".

**Comment by aaaxx** [comment] 2017-11-13 02:14
> Also, we're returning an error for this cue (and thus ignoring this cue) if more or less than 3 digits are specified […]. It doesn't mean that the rest of the cues in the file won't be rendered.

This is a bit hand-wavy. It's not hard to imagine a subtitle app with a lax spec implementation that doesn't zero-pad the timecode, which would make the whole file not render. Here's an [example](https://github.com/SubtitleEdit/subtitleedit/issues/2191) of exactly the millisecond issue mentioned by @nigelmegitt, although in SRT file.

So since you're specifying the actual algorithm, you might as well specify a sensible way to handle the most likely form of malformed timecodes – unpadded values.

And the most logical thing to do is to pad integers and integer part of decimals (hours, minutes, seconds) with _leading_ zeros, and fractional part of decimals (milliseconds) with _trailing_ zeros, since that's the only way to change their formatting without changing their value (the same zeros should also be trimmed in case of overlong values). The rationale being that the authoring app is more likely to just write the correct values without zero-padding them, than it is to trim the significant zeros before writing the values.

**Comment by dwsinger** [comment] 2017-11-13 22:36
Note that the authoring guide (rescued from webplatformdocs, https://www.w3.org/wiki/VTT_Concepts) makes this clear: Miliseconds must have 3 digits and be zero padded if not long enough. This was a decision to be strict with authors and force failures if they weren't clear, made long ago. I would prefer not to change such questions of taste at this point.

**Comment by silviapfeiffer** [comment] 2017-11-18 23:37
@aaaxx As I said: a wrong timecode for a cue will make the cue not render - all other cues that are correctly specified will render. So, if a subtitle app makes a lax implementation, none of their cues will render, which is a good thing, because it will make the implementers realize their error. Otherwise, the error will go unnoticed. This is by design.

It would be wrong to speculate on author intent of "the most likely" interpretation - how much actual data analysis have you done to say that one interpretation is more likely than the other?

**Comment by silviapfeiffer** [comment] 2017-11-18 23:41
Incidentally, the example at https://github.com/SubtitleEdit/subtitleedit/issues/2191 is a good reason why **NOT** to follow the lax SRT specification: even in this issue, people are unsure whether author intent for  "00:00:09,9" was more likely to have been "00:00:09,900" than "00:00:09,009". This is why a specification has to be clear and make incomplete timecodes illegal, thus forcing the software implementers to fix their implementation.

**Comment by nigelmegitt** [comment] 2017-11-23 14:58
> Note that the authoring guide (rescued from webplatformdocs, https://www.w3.org/wiki/VTT_Concepts) makes this clear: Miliseconds must have 3 digits and be zero padded if not long enough. This was a decision to be strict with authors and force failures if they weren't clear, made long ago. I would prefer not to change such questions of taste at this point.

Why is this different from the other parts of the WebVTT spec where the parsing algorithm is deliberately written to be "forgiving" of authoring errors? It strikes me that this is actually a weird exception from the general approach, so if it is a question of taste, this is the bit that _should_ be changed for consistency.

I don't think the presence of an authoring guidance document means we are off the hook here.

**Comment by nigelmegitt** [comment] 2017-11-23 15:02
> people are unsure whether author intent for "00:00:09,9" was more likely to have been "00:00:09,900" than "00:00:09,009"

This isn't really something we need to discuss: every school child learns in their maths lessons how this works. The fact that some authoring tools might erroneously fail to add zeroes between the decimal point and the (1 or 2 digit) number of milliseconds is definitely not this spec's problem.

**Comment by silviapfeiffer** [comment] 2017-11-24 03:23
Can you point me to the authoritative maths lesson that prescribes that? I would have expected it to be zeroes at the end - that's how my maths lesson worked. When somebody charges me  $0.9 then that's 90 cents and not 9 cents in my book.

About "forgiving" of authoring errors: we are! A broken time spec gets interpreted as a valid block, but not a valid cue, so it does not break the file. That's just like a mis-spelled tag results in the tag disappearing rather than the file being broken.

**Comment by nigelmegitt** [comment] 2017-11-24 10:03
> When somebody charges me $0.9 then that's 90 cents and not 9 cents in my book.

I agree completely! That's exactly the point I'm making - it is not ambiguous at all in any normal treatment.

I'm arguing that if an authoring tool wants to convey 9ms but omits the leading zeros so it outputs xxx.9 instead of xxx.009 that's an authoring tool error, but there is a well defined meaning that should be applied, rather than throwing the cue away.

**Comment by dwsinger** [comment] 2017-11-27 23:31
do we have field evidence that this is causing grief? if not, I still incline to doing what the current authoring guides, tools, and specs all say: let the numbering of your digits be three, no more, no less; three shall be the number of thy digits, four shall not be the count, neither 2, excepting that thou then proceed to 3. 5 is right out.

**Comment by nigelmegitt** [comment] 2017-11-28 11:12
I'd say the link at https://github.com/w3c/webvtt/issues/370#issuecomment-345479844 is field evidence that it is causing grief.

**Comment by dwsinger** [comment] 2017-11-28 20:19
It seems that the SRT thread is documenting the grief/confusion that comes from being lax, and the confusion that results if fewer than 3 digits are allowed, so it seems to be making the opposite point from you.

**Comment by silviapfeiffer** [comment] 2017-11-29 00:45
My comment at https://github.com/w3c/webvtt/issues/370#issuecomment-345479651 stands

**Comment by nigelmegitt** [comment] 2017-11-29 11:22
See also #415 regarding timestamp alignment across specifications.

**Comment by dwsinger** [comment] 2017-11-29 17:47
@nigelmegitt the conversation on the SRT thread clearly reveals the confusion and the strong possibility of lost or incorrect interop when the rules are relaxed, that's why I am puzzled.

If we say that the value after the decimal point is in milliseconds, it had better have the right number of digits, as 1.9 means 1 and 9 milliseconds. Only if you say it's in seconds and fractional seconds, and you limit the fraction to at most 3 digits, do you avoid this. But the cat is out of the bag.

I see nothing on that thread that indicates that VTT has an operational problem with this, and changing it looks highly likely to introduce one.

**Comment by nigelmegitt** [comment] 2017-12-01 20:31
> If we say that the value after the decimal point is in milliseconds, it had better have the right number of digits

I agree. But we should not say that the value is in milliseconds. It should be a decimal fraction of seconds. That is what it _looks_ like, so that is what it should be. Also it would mean that a class of well formed time expressions permitted in TTML and SMIL that are not well formed in WebVTT would become well formed in WebVTT.

Logically the only operational problem it would cause is if someone is relying on the fact that cues with some other number of digits than 3 after the decimal point are dropped. If authors are expecting them to be processed correctly but they are being dropped as per the spec, then they will find content begins to work properly. If implementations are processing cues with other than 3 digits after the decimal point, and not dropping them, they are already non-conforming implementations anyway, so _caveat emptor_ to the implementers who have done that. The existing conforming class of documents and implementations are unaffected.

**Comment by silviapfeiffer** [comment] 2017-12-01 21:56
The fact remains that this flexibility was present in SRT and has caused issues with non interoperable implementations (as the example demonstrates) so why would we make that mistake again?

Timestamps in other specifications have to be converted anyway, so a fixed, determinate conversion outcome makes that easier: everything behind the . is milliseconds - simplicity wins.

**Comment by dwsinger** [comment] 2017-12-01 22:07
The operational problem it would cause, as Silvia says, is landing VTT In the same confusion as has happened in SRT, and I cannot think why we'd open that can of worms, when no-one has problems when it's closed.

**Comment by nigelmegitt** [comment] 2017-12-04 10:53
Pointer to the SRT issues please?

> everything behind the . is milliseconds - simplicity wins.

Simplicity seems to be in the eye of the beholder. I'm seeing it the other way, i.e. that simplicity here is _not_ to require 3 digits after the `.` but to treat it as what it looks like. If you really want a weird behaviour like milliseconds, don't use a standard decimal fraction delimiter.

> no-one has problems when it's closed.

I'm amazed if this is the case. When this _does_ cause problems, if we have ended up leaving it as is, treat this as a pre-emptive "I told you so".

**Comment by silviapfeiffer** [comment] 2017-12-08 19:17
@nigelmegitt the SRT issue is the one quote earlier: https://github.com/SubtitleEdit/subtitleedit/issues/2191

It clearly shows what how not specifying a fixed timestamp syntax caused trouble for srt implementations.  We've not had such trouble with WebVTT because it has a fixed 3 digit requirement for milliseconds and we should not introduce such trouble.

I'm going to close this as works-for-me. You can add your disagreement with the resolution through a label.

**Closed by silviapfeiffer** 2017-12-08 19:17 UTC
Labels: WR-CG-rejected, WR-pending

**Comment by zcorpan** [comment] 2017-12-09 13:15
Originally I wanted this to be lax as well. But I researched SRT content back when we implemented webvtt in opera and we concluded that dropping cues was the better approach because it is impossible to guess intent in a useful way for typos in timings.

**Comment by nigelmegitt** [comment] 2017-12-11 17:15
Thanks @zcorpan 

> it is impossible to guess intent 

I think (!) you mean it is possible to guess intent, but you'd have a significant chance of getting it wrong because of inconsistent implementation and authoring practices. But that is SRT, and this is WebVTT, and they're different. Even if people have built strange implementation behaviour in SRT I don't find it convincing that this should be used as a constraint on what we do in WebVTT, particularly because it causes different problems with other parts of the ecosystem.

**Comment by dwsinger** [comment] 2017-12-11 17:57
The point is that experience shows -- and the bug you linked to documents -- that the SRT community got into difficulty over this very issue, and so VTT deliberately chose to not get into the same difficulty. Unless you can show author or implementer report showing difficulty with the current specification -- cases where authors were surprised, I think we should go with the industry experience here and not our gut.

**Comment by nigelmegitt** [comment] 2018-02-14 13:58
Looks like there's not much more to say on this without going round in circles. I certainly have a different view of how timestamps without 3 figures after the decimal point should be treated, and what the spec should say, and I believe this means that we have missed an opportunity for alignment with TTML timestamp syntax, but if there's no change, then labelling this as WR-rejected and WR-commenter-rejected seems to reflect reality.
