### ISSUE TITLE
Wide Review Comment 2017: Algorithmic specification

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#384] opened 2017-09-27 12:26 UTC
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

The algorithmic nature of the processing model is helpful for initial implementations, but it is very difficult to understand and follow and perhaps more importantly looks brittle in case of changes. If a change is needed to the algorithm, it may be challenging for implementers to work out where in their implementations the equivalent change is needed, especially if the implementation has been optimised and does not follow the specification's structure exactly.

**Comment by nigelmegitt** [comment] 2017-09-27 14:47
To add to this, a useful addition (or even replacement) of the algorithmic approach would be a set of statements of the required behaviour defined in terms of implementation outcomes, based on the relevant input parameters. Assuming they are orthogonal statements, varying any individual requirements statements, if necessary, would be much easier. This would also lend itself better to the definition of meaningful tests.

**Comment by silviapfeiffer** [comment] 2017-09-27 20:31
Modern specifications at the W3C are all formulated in algorithmic form and I don't think that WebVTT should be changed to become an exception. The goal of most of the specifications at the W3C are to get them implemented in browsers and to make that work, the specifications need an algorithmic approach, since this is the only way to get interoperable implementations, as has been proven over the years.

A further advantage of this approach is that it allows for making a difference between what is standardised syntax and what provided actual formats a browser parses (see the design principles of HTML around interoperability https://www.w3.org/TR/html-design-principles/#interoperability). WebVTT like HTML does not have a well-formedness constraint, no errors are fatal. This is important in a Web context. An algorithmic specification may seem messy, but it creates more
interoperable implementations, which is the goal of a standard.

Also, could you provide an example of the kind of statements of required behaviour that you'd like to see added? I can only visualise them as examples, but not as actual complete specifications.

**Comment by nigelmegitt** [comment] 2017-09-29 09:16
> algorithmic approach, since this is the only way to get interoperable implementations, as has been proven over the years

It's not really worth an argument about this, but there are plenty of counter-examples, where interoperable implementations have been specified without algorithms. I'd put this more in the style/fashion category than a practical requirement for a spec. I agree that it's one way of achieving interoperability.

As discussed on the call yesterday, another feature of the algorithmic approach in the WebVTT spec is that the file parsing, the cue timings and settings and the cue text parsing rules algorithms are farly long, even though in some cases they do refer to other algorithms. It might help to break them down even more. This is doubly true for the processing model in §6.1.

> could you provide an example of the kind of statements of required behaviour that you'd like to see added?

Actually this may be an entire missing section of the spec - the rendering semantics. We have now a data model, which sort of hints at some rendering semantics, a syntax section, which is clearly not the place to put semantics, and the parsing and rendering sections, which are the processing rules to achieve the semantics. But nowhere are the actual semantics described, even informatively.

For example, if regions are supposed to be bounding boxes within which cues are rendered, but act as clipping rectangles to them, and set up a local coordinate system for positioning, then that needs to be written down in the specification. At the moment I can not see it anywhere. (apologies if this is not actually what is intended - the fact that I can't tell is exactly the problem I'm trying to solve here!)

Then that would be an example of an informative statement associated with a subsection of the processing model, along the lines of "Set the position and size of the cue boxes within the regions using the region origin and width and height as the basis of the coordinate system", or something like that.

A point has been made several times that "explainers" don't belong in the spec document. To an extent, I disagree with that. A "WebVTT for dummies" explainer is beyond what is needed, but It has to be clear at least at some level for implementers and document authors what the intent of the spec is. 

I'm particularly concerned that it is very difficult to write tests to verify either that the algorithms meet the expectations or that an implementation has the same behavioural outcomes as the algorithm in the spec, because those behavioural outcomes are not written down anywhere. I can see a huge list of them at w3c/web-platform-tests/webvtt but I don't understand how they can be derived sensibly from the spec.

**Comment by dwsinger** [comment] 2017-09-29 17:45
This whole discussion is woefully out of place. A wide review occurs when the WG has decided it's OK proceeding, and asks for external review. This is the second such wide review, and for a chair not to realize this seems frankly bizarre. Finally, questions of specification structure were discussed years ago; last-call is not the time to address them. I recommend we close this without action.

**Comment by nigelmegitt** [comment] 2017-09-29 18:47
As far as I know wide review is open to everyone and the scope of review is unspecified. It is entirely reasonable for anyone to review it on whatever basis is relevant to them and provide that feedback. Of course the group has the option to take some or no action and explain this response.

Merely noting that the question is not new is not a reason to dismiss the question. I note that similar points were made in the previous wide review and some effort was made to address them. It is also true that substantive changes have been made to the specification since the previous wide review. On reviewing this time, I find the problem and I report it. I don't think it is reasonable to assess the substantiveness of the comment based on the time when it was made, rather it must be assessed based on the document to which the comment applies.

**Comment by silviapfeiffer** [comment] 2017-10-28 05:13
OK, first of all, can we agree not to change the algorithmic nature of the processing model. If so, this issue should be closed. All other issues should be addressed separately.

To summarise the other concerns:
1/ Break up processing model $6.1 further - I have registered #397 for this
2/ "Rendering semantics" - if you want to continue that discussion, please open a new issue. The semantics of rendering were always left as a reference to CSS.

**Comment by silviapfeiffer** [comment] 2017-11-10 23:54
Resolution at TPAC: this is not the right time to change the algorithmic nature of the processing model, but improve readability

**Comment by silviapfeiffer** [comment] 2017-11-11 03:20
@nigelmegitt I'd like to close this issue

**Comment by silviapfeiffer** [comment] 2017-11-19 00:13
BTW: the PR for #397 is at https://github.com/w3c/webvtt/pull/398

**Comment by nigelmegitt** [comment] 2017-11-24 17:58
Can I just check - when writing tests for an algorithmic style specification, are the tests required to verify that the algorithm is being followed, or that the output of the implementation is the same as the output of the algorithm for all input conditions?

**Comment by silviapfeiffer** [comment] 2017-11-24 22:12
The algorithmic specification is pseudo code. There's no way you can verify that each step is being followed. So it's the latter.

**Comment by nigelmegitt** [comment] 2017-11-27 12:11
Thanks, I thought so. Given that we don't list anywhere the intended behaviour for any particular inputs, in normative terms, except in those algorithms, we are pushing down to testers the task of stepping manually through the algorithm to generate test input conditions and outputs; further, we have limited visibility in the working group of whether those tests reflect the intent of the specifiers, or indeed if they have appropriate coverage of the algorithm. This seems to be a major interoperability problem.

If we were additionally to state normative behaviours that could be used to generate tests, then we could keep the algorithm (which some WG members have stated is a useful resource for implementers) and actually test that the algorithm generates those behaviours. Since the algorithm must already be informative (since adherence to the algorithm is untestable), this status could then be clarified.

**Comment by silviapfeiffer** [comment] 2017-12-02 12:59
Yes, we are requiring testers to step through the algorithm to generate inputs and outputs. So how is that different to requiring testers to read any other type of specification to create inputs and outputs for tests?

The algorithmic nature of the specification in fact makes it easier to write tests, because testers can step through each of the paths in the algorithm to create an output for all pathways. That process results in a full test set for all edge cases. This is much better than writing up random examples throughout the specification and using those as tests.

Also, the spec has normative behaviour coded in the algorithmic way. An implementation has to stick to the meaning of that pseudocode and create the same result as the algorithm. The algorithm is therefore normative.

**Comment by dwsinger** [comment] 2017-12-08 18:22
added @nigelmegitt commeter-agreed-partial and closing (he doesn't like it, but understands that we can't change now)

**Comment by nigelmegitt** [comment] 2017-12-11 15:43
Actually I think we were heading in a different direction @dwsinger and I hadn't had chance to make the next comment in the conversation...

> testers can step through each of the paths in the algorithm to create an output for all pathways.

This seems incredibly painful, and something that the specifiers should be doing. Otherwise at what point do you get to confirm that those pathways are correct or say "oops, no, that's an accidental error, we meant something else"? Only during implementation of tests that are not part of the specification. At that point you have no interoperability, especially if some implementers do it some other way.

If we even had a trail of breadcrumbs that said "we want behaviour X in scenario A", so add step 7 to the algorithm to make that happen, this would be okay, but I haven't ever seen that. The whole thing  seems like a magic recipe.

My proposal for what to change is to add "scenario A => behaviour X" statements, even if they are informative, or an appendix as a set of statements against which to test an implementation.

**Comment by dwsinger** [comment] 2017-12-11 17:53
@nigelmegitt  Can you point us at the equivalent statements in other specs (e.g. TTML, HTML)?

**Comment by silviapfeiffer** [comment] 2017-12-20 17:46
> If we even had a trail of breadcrumbs that said "we want behaviour X in scenario A", so add step 7 to the algorithm to make that happen, this would be okay, but I haven't ever seen that. The whole thing seems like a magic recipe.

> My proposal for what to change is to add "scenario A => behaviour X" statements, even if they are informative, or an appendix as a set of statements against which to test an implementation.

So you're asking for a list of example scenarios, which is what the whole of the Introduction section is.

I'd like to sugges a "works for me" closing of this bug. If need be, with a commenter disagreement.

**Comment by nigelmegitt** [comment] 2018-02-14 17:55
> So you're asking for a list of example scenarios, which is what the whole of the Introduction section is.

@silviapfeiffer I was thinking of something more exhaustive than just a set of examples, something more like a BDD, e.g. "Given a cue with a region setting, and the cue has a "vertical" setting, the cue is positioned relative to the video viewport".

> I'd like to suggest a "works for me" closing of this bug. If need be, with a commenter disagreement.

OK, I do disagree :-) By the way, I think a spec that includes both these intended behaviours _and_ an algorithm to achieve them would be an excellent thing. Implementations could be built according to the algorithm, tested according to the specified behaviours, and any discrepancies caused by issues in the algorithm could then be fixed back in the spec, closing the loop.

**Comment by dwsinger** [comment] 2018-02-19 21:11
I think this is another where we expected to fail to reach consensus...

**Comment by silviapfeiffer** [comment] 2018-02-25 08:44
@nigelmegitt  Having a single spec that contradicts itself by providing two normative descriptions of what it does is not a good spec. The intended behaviours are described in prose as much as possible in the Introduction and in the green standout notes throughout the spec as the concepts are introduced. Prose is not good for providing normative directions, so the prose that describes intended behaviour stays non-normative.

About the example that you posted:
If you have a problem specifically that we haven't defined regions for vertically rendered cues, then that's a specific issue that should be separately addressed. The spec has prose that says that "Specifically, if the cue has a "vertical", "line" or "size" setting, the cue drops out of the region." which should satisfy what you were trying to write.

Any specific changes you would like to have, please open up a new issue. I'm closing this because we will not completely re-write the spec in a different way.

**Closed by silviapfeiffer** 2018-02-25 08:44 UTC
Labels: TPAC-discussed, WR, WR-CG-rejected, WR-commenter-rejected, WR-rejected, WR-spec-updated-partial

**Comment by nigelmegitt** [comment] 2018-02-26 14:29
> If you have a problem specifically that we haven't defined regions for vertically rendered cues,

@silviapfeiffer I was using that for an example only, not intending to raise that as a problem.

> Having a single spec that contradicts itself by providing two normative descriptions of what it does is not a good spec. 

Agreed. They're supposed not to contradict each other. If they do, that's very strong evidence that there's a problem that needs to be fixed. Solving that by just omitting the outcome descriptions that would be useful is a solution to the logical problem, but does not solve the wider problem that having a spec that provides a single normative description of what it does, where that description is only useful to one group of constituents is also not a good spec.

> The intended behaviours are described in prose as much as possible in the Introduction and in the green standout notes throughout the spec as the concepts are introduced.

I disagree with this statement. The actual behaviours are stated algorithmically; it is unclear to what extent the _intended_ behaviours are stated. Further, there's no set of requirements against which to validate the spec.

Clearly by closing this you're indicating that you are unwilling to consider any improvement here. That's understood.

**Comment by dwsinger** [comment] 2018-02-26 18:38
> On Feb 26, 2018, at 6:29 , Nigel Megitt <notifications@github.com> wrote:
> 
> Clearly by closing this you're indicating that you are unwilling to consider any improvement here. That's understood.

I don’t think that’s fair. Specific requests for text can be considered; but the problem as posed is too open-ended.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by nigelmegitt** [comment] 2018-02-27 09:11
> Specific requests for text can be considered

This is symptomatic of the problem: I cannot make specific requests for text because I do not know what behaviour was intended, and it isn't written down anywhere! It seems to be in some folks' heads and there's no way to close the loop to verify that the spec does what it is supposed to do.

In the absence of some documentation of the intended behaviour, I cannot get closer than an open-ended problem statement.
