### ISSUE TITLE
Unused variable "current position score"

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#297] opened 2016-05-30 09:59 UTC
https://w3c.github.io/webvtt/#processing-model

> Let current position score be the percentage of the area of the bounding box of the boxes in boxes that is outside the title area box\.

The variable "current position score" is only used once, and it doesn't be used again.
Do we need to remove it? or we forgot to add the related description?

**Comment by zcorpan** [comment] 2016-05-30 10:10
Duplicate of https://github.com/w3c/webvtt/issues/226

Yes, something is wrong here. I have not investigated yet. Probably we can just remove it.

**Closed by zcorpan** 2016-05-30 10:10 UTC
